const struct global *global      = 0x458B00

# the position of perspective relative to background
const int *perspective           = 0x450BC4

const double _448308             = -5.0
const double _448910             = -1.0
const double _449048             = 5.0
const double _449AF8             = 0.55

const int template_dat           =   0
const int julian_dat             =  52
const int firzen_dat             =  51
const int louisEX_dat            =  50
const int bat_dat                =  38
const int justin_dat             =  39
const int knight_dat             =  37
const int jan_dat                =  36
const int monk_dat               =  35
const int sorcerer_dat           =  34
const int jack_dat               =  33
const int mark_dat               =  32
const int hunter_dat             =  31
const int bandit_dat             =  30
const int deep_dat               =   1
const int john_dat               =   2
const int henry_dat              =   4
const int rudolf_dat             =   5
const int louis_dat              =   6
const int firen_dat              =   7
const int freeze_dat             =   8
const int dennis_dat             =   9
const int woody_dat              =  10
const int davis_dat              =  11
const int stick_dat              = 100
const int hoe_dat                = 101
const int knife_dat              = 120
const int baseball_dat           = 121
const int milk_dat               = 122
const int stone_dat              = 150
const int wooden_box_dat         = 151
const int beer_dat               = 123
const int <_dat                  = 124
const int louis_armour_dat       = 217
const int louis_armour_dat       = 218
const int criminal_dat           = 300
const int john_ball_dat          = 200
const int henry_arrow1_dat       = 201
const int rudolf_weapon_dat      = 202
const int deep_ball_dat          = 203
const int henry_wind_dat         = 204
const int dennis_ball_dat        = 205
const int woody_ball_dat         = 206
const int davis_ball_dat         = 207
const int henry_arrow2_dat       = 208
const int freeze_ball_dat        = 209
const int firen_ball_dat         = 210
const int firen_flame_dat        = 211
const int freeze_column_dat      = 212
const int ice_sword_dat          = 213
const int john_biscuit_dat       = 214
const int dennis_chase_dat       = 215
const int jack_ball_dat          = 216
const int jan_chaseh_dat         = 219
const int jan_chase_dat          = 220
const int firzen_chasef_dat      = 221
const int firzen_chasei_dat      = 222
const int firzen_ball_dat        = 223
const int bat_ball_dat           = 224
const int bat_chase_dat          = 225
const int justin_ball_dat        = 226
const int julian_ball_dat        = 228
const int julian_ball2_dat       = 229
const int etc_dat                = 998
const int broken_weapon_dat      = 999

const int character_type         = 0
const int lignt_weapon_type      = 1
const int heavy_weapon_type      = 2
const int attack_type            = 3
const int throw_weapon_type      = 4
const int criminal_type          = 5
const int drink_type             = 6

const byte facing_right          = 0
const byte facing_left           = 1

const byte false                 = 0
const byte true                  = 1

const int jump_state             = 4
const int dash_state             = 5
const int defend_state           = 7
const int broken_defend_state    = 8
const int catching_state         = 9
const int injured_state_1        = 11
const int falling_state          = 12
const int ice_state              = 13
const int lying_state            = 14
const int injured_state_2        = 16
const int fire_state             = 18
const int burn_run_state         = 19
const int in_the_sky_state_1     = 1000
const int throwing_state         = 1002
const int in_the_sky_state_2     = 2000

const int slightly_injured_frame = 220
const int front_injured_frame    = 222
const int back_injured_frame     = 224

const int not_clone              = -1
