struct itr
  int    kind            # 0x0
  int    x               # 0x4
  int    y               # 0x8
  int    w               # 0xC
  int    h               # 0x10
  int    dvx             # 0x14
  int    dvy             # 0x18
  int    fall            # 0x1C
  int    arest           # 0x20
  int    vrest           # 0x24
  int    respond         # 0x28
  int    effect          # 0x2C
  int    catching_act_1  # 0x30
  int    catching_act_2  # 0x34
  int    caught_act_1    # 0x38
  int    caught_act_2    # 0x3C
  int    bdefend         # 0x40
  int    injury          # 0x44
  int    zwidth          # 0x48
  int    _unknown4C      # 0x4C
